[package]
name = "release-experiment-inner-crate"
version = "0.3.2-branch-name.0"
authors = ["folex <0xdxdy@gmail.com>"]
edition = "2018"
description = "Experimenting with semver on crates.io"
license = "MIT"

[dependencies]
